// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "OI.h"



std::shared_ptr<OI> OI::self;

std::shared_ptr<OI> OI::getInstance() {
	if (! self) {
		self = std::make_shared<OI>;
	}
	return self;
}

OI::OI()
: driver(new Joystick(0))
,dA(driver.get(), kButtonA_ID)
,dB(driver.get(), kButtonB_ID)
,dX(driver.get(), kButtonX_ID)
,dY(driver.get(), kButtoY_ID)
,dLB(driver.get(), kButtonLB_ID)
,dRB(driver.get(), kButtonRB_ID)
,dL3(driver.get(), kButtonL3_ID)
,dR3(driver.get(), kButtonR3_ID)
,dStart(driver.get(), kButtonStart_ID)
,dBack(driver.get(), kButtonBack_ID)

,coDriver(new Joystick(1))
,coA(coDriver.get(, kButtonA_ID))
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    // SmartDashboard Buttons
    SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
